# Generated by Django 4.1.4 on 2022-12-14 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('code_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='snippet',
        ),
        migrations.AddField(
            model_name='snippet',
            name='tag',
            field=models.ManyToManyField(to='code_catalog.tag'),
        ),
    ]
